
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pshcwcgumsxcazimiaev.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBzaGN3Y2d1bXN4Y2F6aW1pYWV2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0MzA0MTQsImV4cCI6MjA2MzAwNjQxNH0.XPgnNe6rN5y-_-LS2DLmhG0bxrUDwCGwIg1o1gfpQeM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storage: localStorage
  }
});

// Create a function to get a tenant-specific Supabase client
export const getTenantSupabaseClient = (tenantUrl: string, tenantKey: string) => {
  return createClient<Database>(tenantUrl, tenantKey, {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
      storage: localStorage
    }
  });
};
